[project]
name = "fuckingfast-batch-download"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofile>=3.8.8",
    "cli2gui>=2024.1",
    "fuckingfast-batch-download",
    "playwright>=1.47.0",
    "tqdm>=4.66.5",
    "xdialog>=1.2.0.1",
]
license = { text = "MIT" }

[tool.uv.sources]
fuckingfast-batch-download = { workspace = true }
