on:
    push:
permissions:
    contents: write
jobs:
    release:
        name: Release on ${{ matrix.target }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - target: aarch64-macos
                      os: macos-latest
                    - target: x86_64-linux
                      os: ubuntu-latest
                    - target: x86_64-windows
                      os: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v5
            - name: Cache
              id: cache-main
              uses: actions/cache@v4
              with:
                path: build
                key: ${{ runner.os }}-main
            - name: Build with pyinstaller
              run: bash -x ./utils/with-chromium.sh
            - name: Prepare assets
              shell: bash
              run: |
                tar -cvzf ${{ matrix.target }}.tar.gz dist
            - name: Upload to Release
              uses: softprops/action-gh-release@v2
              with:
                files: ${{ matrix.target }}.tar.gz
                tag_name: nightly
                prerelease: false
                make_latest: true
